name: Project specific tests
description: Run project specific tests
runs:
  using: composite
  steps:
      - name: Run autograding
        uses: education/autograding@v1



      - name: Checking merge_bed (input input)
        run: |
          if ! cmp <(python3 src/merge_bed.py data/input-sorted.bed data/input-sorted.bed) data/input-merged.bed; then
            echo "Incorrect output for python3 src/merge_bed.py data/input-sorted.bed data/input-sorted.bed"
            diff <(python3 src/merge_bed.py data/input-sorted.bed data/input-sorted.bed) data/input-merged.bed
          fi
        shell: bash


      - name: Checking query_bed (query-1)
        run: |
          if ! cmp <(python3 src/query_bed.py data/large-sorted.bed data/query-1.txt) data/expected-1.txt; then
            echo "Incorrect output for python3 src/query_bed.py data/large-sorted.bed data/query-1.txt"
            diff <(python3 src/query_bed.py data/large-sorted.bed data/query-1.txt) data/expected-1.txt
          fi
        shell: bash

      - name: Checking query_bed (query-2)
        run: |
          if ! cmp <(python3 src/query_bed.py data/large-sorted.bed data/query-2.txt) data/expected-2.txt; then
            echo "Incorrect output for python3 src/query_bed.py data/large-sorted.bed data/query-2.txt"
            diff <(python3 src/query_bed.py data/large-sorted.bed data/query-2.txt) data/expected-2.txt
          fi
        shell: bash

      - name: Checking query_bed (query-3)
        run: |
          if ! cmp <(python3 src/query_bed.py data/large-sorted.bed data/query-3.txt) data/expected-3.txt; then
            echo "Incorrect output for python3 src/query_bed.py data/large-sorted.bed data/query-3.txt"
            diff <(python3 src/query_bed.py data/large-sorted.bed data/query-3.txt) data/expected-3.txt
          fi
        shell: bash